### ISSUE TITLE
Consumer - Profile - sharecode empty popup is displaying- when net is slow

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/goldmenu#148]
Consumer - Profile - sharecode empty popup is displaying- when net is slow

![Screenshot_2019-06-15-16-13-11-63](https://user-images.githubusercontent.com/45225727/59581784-9f905600-90f3-11e9-82ab-41e71d9c8d15.png)

**Comment by ijazakram** [comment]
@KrishnaVittal  Did you miss this functionality testing before update binary to the client?
