### ISSUE TITLE
Address- choose country dropdownlist is  Not updating 

### ISSUE THREAD

**Issue by LalithaCharla** [KrishnaVittal/goldmenu#302]
Choose country  dropdown list is not updating 

![before updating](https://user-images.githubusercontent.com/35054743/69898438-a9df9d00-137f-11ea-9c06-58622cb818ac.JPG)

![after saved](https://user-images.githubusercontent.com/35054743/69898442-b6fc8c00-137f-11ea-9d63-60ee95737d38.JPG)

**Comment by KrishnaVittal** [comment]
Choose country drop down has to remove or hide from the page...
