### ISSUE TITLE
OFFER DEALS (MERCHANT BUTTON):

### ISSUE THREAD

**Issue by KrishnaVittal** [KrishnaVittal/goldmenu#41]
I ALREADY HAVE A GOLDMENU MEMBERSHIP
What is the purpose of sending the OPT phone verification to an account that exists? Isn’t the user email and PIN enough?

**Comment by pvdileepkumar** [comment]
What was the fixed one Email/Phone Number ? while on (1) merchant registration (2) consumer social login and (3) consumer registration through email/phone ? @KrishnaVittal

**Comment by pvdileepkumar** [comment]
What was the fixed one Email/Phone Number ? while on (1) merchant registration (2) consumer social login and (3) consumer registration through email/phone ? @KrishnaVittal
